import {
  Play,
  Brain,
  HelpCircle,
  KeyRound,
  Database,
  Webhook,
  GitBranch,
  CheckCircle2,
  CreditCard,
  Repeat,
  Wrench,
  CalendarClock,
  PhoneForwarded,
  PhoneCall,
  Flag,
} from 'lucide-react';
import type { WorkflowNodeType } from '../../types/config';

export const NODE_ICONS: Record<WorkflowNodeType, typeof Play> = {
  start: Play,
  'detect-intent': Brain,
  'ask-question': HelpCircle,
  authenticate: KeyRound,
  'retrieve-account': Database,
  'api-request': Webhook,
  condition: GitBranch,
  confirmation: CheckCircle2,
  payment: CreditCard,
  'plan-change': Repeat,
  'technical-diagnostic': Wrench,
  'schedule-appointment': CalendarClock,
  'transfer-agent': PhoneForwarded,
  'schedule-callback': PhoneCall,
  end: Flag,
};

export const NODE_COLORS: Record<WorkflowNodeType, string> = {
  start: 'var(--color-success)',
  'detect-intent': 'var(--chart-1)',
  'ask-question': 'var(--chart-4)',
  authenticate: 'var(--chart-3)',
  'retrieve-account': 'var(--chart-2)',
  'api-request': 'var(--chart-7)',
  condition: 'var(--chart-4)',
  confirmation: 'var(--color-success)',
  payment: 'var(--chart-6)',
  'plan-change': 'var(--chart-3)',
  'technical-diagnostic': 'var(--chart-2)',
  'schedule-appointment': 'var(--chart-5)',
  'transfer-agent': 'var(--color-danger)',
  'schedule-callback': 'var(--chart-6)',
  end: 'var(--color-gray-600)',
};
